### ISSUE TITLE
Conflicting dependencies when used with OneSignal plugin

### ISSUE THREAD

**Issue by FredTSousa** [NicolaasZA/cordova-plugin-ia-mlkit-scanner#1]
Hello, by looking at the code this version seems to have everything firebase/related commented which means it shouldn't need it,

Am i correct? is this an implementation of the mlkit without firebase?

https://developers.google.com/ml-kit/vision/barcode-scanning/android

**Comment by NicolaasZA** [comment]
Hi Fred. The plugin is build on Google MLKit.

It was originally designed to use MLKit when it was under Firebase.  It is however coded to use the model in Google Play Services. 

https://developers.google.com/ml-kit/vision/barcode-scanning/android#before-you-begin (Step 3)

**Comment by NicolaasZA** [comment]
I removed the commented firebase imports in a new commit.
https://github.com/NicolaasZA/cordova-plugin-ia-mlkit-scanner/commit/844b667890986946b25bae68194e7b03ca34d609

**Comment by NicolaasZA** [comment]
So short answer is no, you do not need Firebase.

**Comment by FredTSousa** [comment]
Ok, thanks a lot for answering! 
My issue is that I'm also using onesignal and this is giving dependency issues (jetified-firebase-common-18.0.0-runtime  and jetified-firebase-components-16.1.0-runtime) , 16.1.0-runtime is from here, i just cannot find where to remove this, it shouldn't need it anymore right?

**Comment by FredTSousa** [comment]
Just FYI,

managed to be able to build by forcing the removal of the dependency with the 
configurations{
    all*.exclude group: 'com.google.firebase', module: 'firebase-components'
}

But it does  need it since i get errors at runtime about not finding the classes that were in the dependency.

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/components/ComponentDiscovery;
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at com.google.mlkit.common.sdkinternal.MlKitContext.zza(com.google.mlkit:common@@17.2.0:2)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at com.google.mlkit.common.internal.MlKitInitProvider.onCreate(com.google.mlkit:common@@17.2.0:3)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at com.google.mlkit.common.internal.MlKitInitProvider.attachInfo(com.google.mlkit:common@@17.2.0:3)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7624)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7103)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6976)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:257)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:236)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8056)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
08-24 17:40:15.233  4526  4526 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)`

In order for this plugin to work with other more recent plugins that use firebase we need to either be able to remove the dependency but keep the plugin working, or somehow change the dependecy to be the firebase.common which apparently is more recent and has the same classes.

Very thankful for your help so far, I'll keep investigating as much as i can!

**Comment by NicolaasZA** [comment]
I've not used OneSignal before so I am not familiar with their plugins.

It could very well be that MLKit still uses firebase under the hood.

So perhaps the conflict is because the mlkit-scanner plugin is not using the latest mlkit dependency (com.google.mlkit:barcode-scanning) as it is using 16.1.2 and latest is 17.0.2

There will likely be changes to the code needed to upgrade it from 16 to 17, which I will look into over the weekend.

I also cleaned up the code a bit with the latest version of mlkit-scanner which I released yesterday, versioned as 1.1.3

If you can update to that one and try again? Perhaps it works.

**Comment by NicolaasZA** [comment]
Update: So the migration was rather simple. One import to fix on Android.

Version 1.1.4 on NPM is set to use the latest dependencies. Perhaps this plays nice with other plugins needing Firebase.

**Comment by NicolaasZA** [comment]
https://mvnrepository.com/artifact/com.google.mlkit/barcode-scanning/17.0.2 

partial dependency tree:
- com.google.android.gms » play-services-mlkit-barcode-scanning | 18.0.0
  - com.google.firebase » firebase-components | 16.1.0
  - com.google.firebase » firebase-encoders | 16.1.0
  - com.google.firebase » firebase-encoders-json | 17.1.0

**Then with OneSignal's plugin:**

https://mvnrepository.com/artifact/com.onesignal/OneSignal/4.8.2

partial dependency tree:
- com.google.firebase » firebase-messaging | 22.0.0
  - com.google.firebase » firebase-common | 20.0.0
  - com.google.firebase » firebase-components | 17.0.0
  - com.google.firebase » firebase-datatransport
  - com.google.firebase » firebase-iid-interop | 17.1.0
  - com.google.firebase » firebase-installations | 17.0.0
  - com.google.firebase » firebase-installations-interop | 17.0.0
  - com.google.firebase » firebase-measurement-connector | 19.0.0

There are version mismatches between the two, not sure if its possible to align them.

**Comment by FredTSousa** [comment]
Thank you so much for your help, I guess I don't get why google is using
firebase components on this 2022 version since the last update on
components is in 2021 and components and common (which is updated recently)
have duplicated classes.

I guess I don't have to use onesignal and I can use regular firebase for
push notifications but I'm betting I'll run onto the same issues but if I
get it working somehow I'll let you know!

**Comment by NicolaasZA** [comment]
Hey, I see you reforked and changed **runtimeOnly** to **implementation** in _build-extras.gradle_
and also added com.google.firebase:firebase-bom:28.0.1

Did this solve the problem for you?

**Comment by FredTSousa** [comment]
Hey,

I was able to successfully build with it together with onesignal but then
onesignal had an error on runtime that honestly I can't figure out if it's
due to this or not so not sure.

It didnt work to build together with firebase push notifications.

So I would say no it did not.

Best regards
